#!/bin/sh

# Uncomment the following two lines for normal desktop:
#unset SESSION_MANAGER
#exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
#dbus-launch --exit-with-session gnome-session &
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
#
##gnome
gnome-panel &
gnome-settings-daemon &
metacity &
nautilus &

#kde
# Red Hat Linux VNC session startup script
#unset SESSION_MANAGER
#exec /usr/bin/startkde

#xfce
#startxfce4 &

#lxde
#lxterminal &
#/usr/bin/lxsession -s LXDE &
